/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import logica.Agente;
import logica.PreProcesador;
import logica.Utils;
import respuestas.Respuesta;

public class InterfazPorVoz extends javax.swing.JFrame {

    Agente agente;
    
    public InterfazPorVoz() {
        initComponents();
        
        agente = new Agente();
        
        this.decirRespuesta("Puedes no responder a esa pregunta.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnHablar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ChatBot");

        btnHablar.setText("Hablar");
        btnHablar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHablarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHablar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHablar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHablarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHablarActionPerformed
        String hablado = this.reconocerEntrada();
        obtenerRespuestas(hablado);
    }//GEN-LAST:event_btnHablarActionPerformed
    
    private String reconocerEntrada(){
        String respuesta = "";
        try{
            //TODO: Hacer metodo
        }
        catch(Exception ex){
            ex.printStackTrace();
        }
        return respuesta;
    }
    
    private void decirRespuesta(String respuesta){
        //TODO: Hacer metodo
    }
    
    private void obtenerRespuestas(String textoEntrada){
        try{
            if(!textoEntrada.trim().equals("")){
                int repeticionesPalabrasClaves;
                for(Respuesta respuesta : agente.generarRespuesta(textoEntrada)){
                    repeticionesPalabrasClaves = Utils.obtenerRepeticionesPalabrasClaves(agente.getReglaDatoUsadas(), PreProcesador.obtenerPalabras(textoEntrada));
                    respuesta.ejecutar(repeticionesPalabrasClaves);
                    this.decirRespuesta(respuesta.toString(repeticionesPalabrasClaves));
                }
            }
        }
        catch(Exception ex){
            ex.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHablar;
    // End of variables declaration//GEN-END:variables
}
