package interfaz;

import criterios.Criterio;
import historial.Historial;
import reglas.ReglaDato;
import java.util.ArrayList;
import java.util.List;
import logica.Agente;
import logica.Utils;

public class Logs extends javax.swing.JFrame {
    
    private static final double TAMAÑO_PIXELES_GUION = 4.2;
    private Agente agente;
    
    public Logs(Agente agente) {
        initComponents();
        int cantidadGuiones = ((int)(taLogs.getSize().getWidth()/TAMAÑO_PIXELES_GUION));
        List<String> logs = Historial.obtenerHistorial(agente.getReglaDatoUsadas());
        String texto = "";
        String log;
        for(int i = 0; i<logs.size(); i++){
            log = logs.get(i);
            texto += log;
            texto += ((texto.equals("")) ? "" : "\n");
            for(int j=0; j<cantidadGuiones; j++){
                texto += "-";
            }
            if(i < logs.size() - 1){
                texto += "\n";
            }
        }
        taLogs.setText(texto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        taLogs = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Logs");

        taLogs.setEditable(false);
        taLogs.setColumns(20);
        taLogs.setRows(5);
        jScrollPane1.setViewportView(taLogs);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taLogs;
    // End of variables declaration//GEN-END:variables
}
